import { Command } from 'commander';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { execSync } from 'child_process';

export const initCommand = new Command('init')
    .description('Initialize a new Apollo Gears project')
    .argument('[projectName]', 'Name of the project directory')
    .action(async (projectName) => {
        // 1. Prompt for Project Name if missing
        if (!projectName) {
            const answers = await inquirer.prompt([
                {
                    type: 'input',
                    name: 'name',
                    message: 'What is the name of your project?',
                    default: 'my-apollo-app',
                    validate: (input) => input.trim() !== '' ? true : 'Project name is required'
                }
            ]);
            projectName = answers.name;
        }

        const projectRoot = path.join(process.cwd(), projectName);

        if (fs.existsSync(projectRoot)) {
            console.error(chalk.red(`Error: Directory "${projectName}" already exists.`));
            process.exit(1);
        }

        console.log(chalk.blue(`\n🚀 Initializing project in ${projectRoot}...\n`));

        try {
            // 2. Create Directory
            await fs.ensureDir(projectRoot);

            // 3. Create Package.json
            const packageJson = {
                name: projectName,
                version: "1.0.0",
                description: "Backend project generated by Apollo Gears CLI",
                main: "dist/server.js",
                scripts: {
                    "start": "node dist/server.js",
                    "dev": "ts-node-dev --respawn --transpile-only src/server.ts",
                    "build": "tsc",
                    "lint": "eslint src/**/*.ts",
                    "lint:fix": "eslint src/**/*.ts --fix",
                    "format": "prettier --write ."
                },
                keywords: ["express", "prisma", "typescript", "apollo-gears"],
                author: "",
                license: "ISC",
                dependencies: {
                    "express": "^4.18.2",
                    "cors": "^2.8.5",
                    "dotenv": "^16.3.1",
                    "http-status": "^1.7.3",
                    "@prisma/client": "^5.7.1"
                },
                devDependencies: {
                    "typescript": "^5.3.3",
                    "ts-node-dev": "^2.0.0",
                    "@types/node": "^20.10.4",
                    "@types/express": "^4.17.21",
                    "@types/cors": "^2.8.17",
                    "prisma": "^5.7.1",
                    "eslint": "^8.55.0",
                    "prettier": "^3.1.1"
                }
            };
            await fs.writeJson(path.join(projectRoot, 'package.json'), packageJson, { spaces: 2 });

            // 4. Create tsconfig.json
            const tsconfig = {
                "compilerOptions": {
                    "target": "ES2021",
                    "module": "commonjs",
                    "moduleResolution": "node",
                    "outDir": "./dist",
                    "rootDir": "./src",
                    "strict": true,
                    "esModuleInterop": true,
                    "skipLibCheck": true,
                    "forceConsistentCasingInFileNames": true
                },
                "include": ["src/**/*"],
                "exclude": ["node_modules"]
            };
            await fs.writeJson(path.join(projectRoot, 'tsconfig.json'), tsconfig, { spaces: 2 });

            // 5. Create Scaffolding Folders
            const folders = [
                'src/app/modules',
                'src/app/middlewares',
                'src/app/routes',
                'src/app/utils',
                'src/app/errors',
                'src/app/config'
            ];
            for (const folder of folders) {
                await fs.ensureDir(path.join(projectRoot, folder));
            }

            // 6. Create Essential Files
            // src/server.ts
            const serverContent = `import app from './app';
import config from './app/config';

async function main() {
  try {
    app.listen(config.port, () => {
      console.log(\`Example app listening on port \${config.port}\`);
    });
  } catch (err) {
    console.log(err);
  }
}

main();`;
            await fs.writeFile(path.join(projectRoot, 'src/server.ts'), serverContent);

            // src/app.ts
            const appContent = `import express, { Application, Request, Response } from 'express';
import cors from 'cors';

const app: Application = express();

// parsers
app.use(express.json());
app.use(cors());

// application routes
// app.use('/api/v1', router);

app.get('/', (req: Request, res: Response) => {
  res.send('Hello from Apollo Gears World!');
});

export default app;`;
            await fs.writeFile(path.join(projectRoot, 'src/app.ts'), appContent);

            // src/app/config/index.ts
            const configContent = `import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(process.cwd(), '.env') });

export default {
  port: process.env.PORT,
  database_url: process.env.DATABASE_URL,
};`;
            await fs.writeFile(path.join(projectRoot, 'src/app/config/index.ts'), configContent);

            // .env
            const envContent = `PORT=5000
DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"`;
            await fs.writeFile(path.join(projectRoot, '.env'), envContent);

            // .gitignore
            const gitignoreContent = `node_modules
dist
.env`;
            await fs.writeFile(path.join(projectRoot, '.gitignore'), gitignoreContent);

            console.log(chalk.green('\n✅ Project structure created successfully!'));

            // 7. Install Dependencies Prompt
            const { install } = await inquirer.prompt([
                {
                    type: 'confirm',
                    name: 'install',
                    message: 'Would you like to install dependencies now?',
                    default: true
                }
            ]);

            if (install) {
                console.log(chalk.yellow('\n📦 Installing dependencies...'));
                execSync('npm install', { cwd: projectRoot, stdio: 'inherit' });
                console.log(chalk.green('\n✅ Dependencies installed!'));
            }

            console.log(chalk.cyan(`\nTo get started:\n  cd ${projectName}\n  ${install ? 'npm run dev' : 'npm install && npm run dev'}\n`));

        } catch (error) {
            console.error(chalk.red('❌ Initialization failed:'), error);
            process.exit(1);
        }
    });
